'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property AddressID As Integer
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property StateProvinceID As Integer
    Public Property PostalCode As String
    Public Property SpatialLocation As System.Data.Entity.Spatial.DbGeography
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property SalesOrderHeader As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)
    Public Overridable Property SalesOrderHeader1 As ICollection(Of SalesOrderHeader) = New HashSet(Of SalesOrderHeader)

End Class
