'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AdventureWorks2014
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AdventureWorks2014")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Address() As DbSet(Of Address)
    Public Overridable Property ContactType() As DbSet(Of ContactType)
    Public Overridable Property Product() As DbSet(Of Product)
    Public Overridable Property SalesOrderDetail() As DbSet(Of SalesOrderDetail)
    Public Overridable Property SalesOrderHeader() As DbSet(Of SalesOrderHeader)

End Class
