'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalesOrderDetail
    Public Property SalesOrderID As Integer
    Public Property SalesOrderDetailID As Integer
    Public Property CarrierTrackingNumber As String
    Public Property OrderQty As Short
    Public Property ProductID As Integer
    Public Property SpecialOfferID As Integer
    Public Property UnitPrice As Decimal
    Public Property UnitPriceDiscount As Decimal
    Public Property LineTotal As Decimal
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property SalesOrderHeader As SalesOrderHeader

End Class
