'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalesOrderHeader
    Public Property SalesOrderID As Integer
    Public Property RevisionNumber As Byte
    Public Property OrderDate As Date
    Public Property DueDate As Date
    Public Property ShipDate As Nullable(Of Date)
    Public Property Status As Byte
    Public Property OnlineOrderFlag As Boolean
    Public Property SalesOrderNumber As String
    Public Property PurchaseOrderNumber As String
    Public Property AccountNumber As String
    Public Property CustomerID As Integer
    Public Property SalesPersonID As Nullable(Of Integer)
    Public Property TerritoryID As Nullable(Of Integer)
    Public Property BillToAddressID As Integer
    Public Property ShipToAddressID As Integer
    Public Property ShipMethodID As Integer
    Public Property CreditCardID As Nullable(Of Integer)
    Public Property CreditCardApprovalCode As String
    Public Property CurrencyRateID As Nullable(Of Integer)
    Public Property SubTotal As Decimal
    Public Property TaxAmt As Decimal
    Public Property Freight As Decimal
    Public Property TotalDue As Decimal
    Public Property Comment As String
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property Address As Address
    Public Overridable Property Address1 As Address
    Public Overridable Property SalesOrderDetail As ICollection(Of SalesOrderDetail) = New HashSet(Of SalesOrderDetail)

End Class
